Rails.application.config.assets.precompile += %w( index-click-handler.js )
Rails.application.config.assets.precompile += %w( textfield-handler.js )
Rails.application.config.assets.precompile += %w( show/init-script.js )
Rails.application.config.assets.precompile += %w( show/particle-system-handler.js )
Rails.application.config.assets.precompile += %w( show/tree-list-script.js )
Rails.application.config.assets.precompile += %w( show/operations.js )