Rails.application.config.assets.precompile += %w( index-click-handler.js )
Rails.application.config.assets.precompile += %w( textfield-handler.js )
Rails.application.config.assets.precompile += %w( getonto.js )
Rails.application.config.assets.precompile += %w( tree-test.js )
Rails.application.config.assets.precompile += %w( tree-script.js )